baseURL = 'https://tddinswift.com/'
languageCode = 'en-us'
title = 'TDD in Swift'
theme = 'blank-canvas'

[permalinks]
  posts = '/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
